:toc: right

# Next version of devonfw website

image:https://github.com/devonfw-forge/official-website/workflows/build-and-deploy/badge.svg[link="https://github.com/devonfw-forge/official-website/actions"] 

## Collaboration

In addition to the github issues, we are maintaining a project board on https://app.zenhub.com/workspaces/devonfw-website-5d847a381201de0001b6a798/board?repos=204906646[ZenHub] to track the current status.

## Dependencies

* http://de-mucevolve02/files/devonfw/current/[devonfw distribution]

## Initial setup

* Open the console in your devonfw distribution (console.bat).
* Clone this project `git clone --recurse-submodules https://github.com/devonfw-forge/official-website.git`.

## Build
* Inside `/official-website/` run `mvn clean package -Doutput.format=html`.
** _Remark_: for your own trials, it might be worth, to go into `/official-website/devonfw-guide/` and delete all *.wiki folders to speed up build as you might not want to generate the complete docs section of the website.

## Run
* Option 1:
** Install http-server from npm: `npm install -g http-server`
** run `http-server target/generated-docs/ -o`. The default port used will be 8080 but a different one can be specified using the argument `-p port-number`.
* Option 2:
** run `python -m http.server -d target/generated-docs/  port-number`.

Now you will be able to go to http://localhost:<port-number>/index.html.

## Deployment

The deployment of the website is automatically done by the GitHub Action https://github.com/devonfw-forge/official-website/actions?workflow=build-and-deploy[build-and-deploy] on each commit.

