= PWA

[.directory]
== PWA

Progresive web applications (PWAs) are web application that offer better user experience than the traditional ones. In general, they solve problems related with reliability and speed:

Reliability: PWAs are stable. In this context stability means than even with slow connections or even with no network at all, the application still works. To achieve this, some basic resources like styles, fonts, requests, … are stored; due to this caching, it is not possible to assure that the content is always up-to-date.

Speed: When an users opens an application, he or she will expect it to load almost inmediately (almost 53% of users abandon sites that take longer that 3 seconds, source: https://developers.google.com/web/progressive-web-apps/#fast).

[.links-to-files]
== Related

[.common-links]
=== Links

[.devon4j-links]
=== devon4j Links

[.devon4net-links]
=== devon4net Links

[.devon4ng-links]
=== devon4ng Links

<</website/pages/docs/master-devon4ng.asciidoc_angular.html#guide-angular-pwa.asciidoc, Angular PWA>>

<</website/pages/docs/master-devon4ng.asciidoc_ionic.html#guide-ionic-pwa.asciidoc, Ionic 4 PWA>>

[.devon4node-links]
=== devon4node Links

[.videos-links]
=== Video Links

