:toc: macro
toc::[]
:idprefix:
:idseparator: -

= Testing Framework Basics

== Framework Overview

To use the framework the user should be familiar with at least *these three packages* inside of the root directory _allure-app-under-test_:

* _src/main/java_
+
_Page Object_ classes should be placed in this directory. A few examples come pre-installed on the framework, you can find them in _pages_:
+
[source]
----
allure-app-under-test
	src/main/java
		selenium
			pages
----
+
Create a custom package under _pages_ when creating a new project.

* _src/test/java_
+
This path contains the test case classes. Again, a few examples are included within the framework. They are available in _tests_:
+
[source]
----
allure-app-under-test
	src/test/java
		selenium.tests
			tests
----
+
Create a custom package under _tests_ when creating a new project.

* _src/test/resources_
+
This directory contains test resources (logs, outputs, data, etc).

== Framework Components

After the initial overview, two components stand out that will be explained in the following chapter: Page Objects and Test Classes.

